site_name: Example pdf parser application using GROBID
nav:
  - Home: description.md
  - Install: install.md
theme:
  name: material

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true